name: prismlauncher-alpo
title: Prism Launcher
base: core24
version: '10.0.5'
adopt-info: prismlauncher
license: GPL-3.0
website: https://prismlauncher.org
contact: https://github.com/alponaut/prismlauncher-snap/issues
issues: https://github.com/alponaut/prismlauncher-snap/issues
source-code: https://github.com/alponaut/prismlauncher-snap
summary: Custom Minecraft Launcher to easily manage multiple Minecraft installations

grade: stable
confinement: strict

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]

layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libflite.so:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libflite.so.1
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libflite_cmu_us_kal16.so:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libflite_cmu_us_kal16.so.1
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/alsa-lib:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/alsa-lib

apps:
  prismlauncher:
    extensions: [kde-neon-6]
    command: usr/bin/prismlauncher
    desktop: usr/share/applications/org.prismlauncher.PrismLauncher.desktop
    common-id: org.prismlauncher.PrismLauncher
    plugs:
      - audio-record
      - joystick
      - home
      - screen-inhibit-control

parts:
  prismlauncher:
    plugin: cmake
    source: https://github.com/PrismLauncher/PrismLauncher.git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    override-pull: |
      craftctl default
      patch -p1 < $CRAFT_PROJECT_DIR/patches/fixshortcut.patch
    parse-info:
      - usr/share/metainfo/org.prismlauncher.PrismLauncher.metainfo.xml
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DBUILD_TESTING=OFF
      - -DLauncher_BUILD_PLATFORM=snap
      - -DLauncher_ENABLE_JAVA_DOWNLOADER=ON
    build-packages:
      - cmark
      - ninja-build
      - extra-cmake-modules
      - openjdk-17-jdk
      - libgl1-mesa-dev
      - duktape-dev
      - libarchive-dev
      - libtomlplusplus-dev
      - libproxy-dev
      - libxkbcommon-dev
      - libvulkan-dev
      - libcmark-dev
      - libqrencode-dev
      - pkg-config
      - gamemode-dev
    stage-packages:
      - x11-xserver-utils
      - libtomlplusplus3t64
      - libcmark0.30.2
      - flite
      - gamemode
      - libasound2t64
      - libasound2-plugins
      - libpulse0
  
  cleanup:
    after:
      - prismlauncher
    plugin: nil
    build-snaps:
      - core24
      - kf6-core24
      - mesa-2404
    override-prime: |
      set -eux
      for snap in "core24" "kf6-core24" "mesa-2404"; do
          cd "/snap/$snap/current" && find . -type f,l -exec rm -rf "$CRAFT_PRIME/{}" \;
      done
