name: prismlauncher-alpo
title: Prism Launcher
base: core24
adopt-info: prismlauncher
license: GPL-3.0
website: https://prismlauncher.org
contact: https://github.com/alponaut/prismlauncher-snap/issues
issues: https://github.com/alponaut/prismlauncher-snap/issues
source-code: https://github.com/alponaut/prismlauncher-snap
summary: Custom Minecraft Launcher to easily manage multiple Minecraft installations

grade: stable
confinement: strict

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]

layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/alsa-lib:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/alsa-lib
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libtomlplusplus.so.3:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libtomlplusplus.so.3
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libcmark.so.0.30.2:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libcmark.so.0.30.2
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libflite.so:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libflite.so.1
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libflite_cmu_us_kal16.so:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libflite_cmu_us_kal16.so.1

apps:
  prismlauncher:
    extensions: [kde-neon-6]
    command: usr/bin/prismlauncher
    common-id: org.prismlauncher.PrismLauncher
    desktop: usr/share/applications/org.prismlauncher.PrismLauncher.desktop
    plugs:
      - audio-record
      - joystick
      - home
      - screen-inhibit-control

parts:
  prismlauncher:
    plugin: cmake
    source: https://github.com/PrismLauncher/PrismLauncher.git
    override-pull: |
      set -e
      LATEST_TAG=$(curl -s https://api.github.com/repos/PrismLauncher/PrismLauncher/releases/latest | jq -r .tag_name)
      craftctl default
      git checkout "$LATEST_TAG"
      craftctl set-version "${LATEST_TAG}"
      patch -p1 < $CRAFT_PROJECT_DIR/patches/fix-shortcuts.patch
      patch -p1 < $CRAFT_PROJECT_DIR/patches/remove-application-dir-shortcut.patch
    parse-info:
      - usr/share/metainfo/org.prismlauncher.PrismLauncher.metainfo.xml
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DLauncher_BUILD_PLATFORM=snap
      - -DLauncher_ENABLE_JAVA_DOWNLOADER=ON
      - -DLauncher_BUG_TRACKER_URL=https://github.com/alponaut/prismlauncher-snap/issues
    build-packages:
      - curl
      - git
      - jq
      - cmake
      - ninja-build
      - extra-cmake-modules
      - pkg-config
      - cmark
      - gamemode-dev
      - libarchive-dev
      - libcmark-dev
      - libgl1-mesa-dev
      - libqrencode-dev
      - libtomlplusplus-dev
      - libvulkan-dev
      - zlib1g-dev
      - openjdk-17-jdk
    stage-packages:
      - libarchive13t64
      - libcmark0.30.2
      - libqrencode4
      - libtomlplusplus3t64
      - libvulkan1
      - zlib1g
      - pciutils
      - mesa-utils
      - x11-xserver-utils
      - gamemode
      - libflite1
      - libasound2-plugins
  
  cleanup:
    after:
      - prismlauncher
    plugin: nil
    build-snaps:
      - core24
      - kf6-core24
      - mesa-2404
    override-prime: |
      set -eux
      for snap in "core24" "kf6-core24" "mesa-2404"; do
          cd "/snap/$snap/current" && find . -type f,l -exec rm -rf "$CRAFT_PRIME/{}" \;
      done
